'use strict';
const $ = id => document.getElementById(id);
const REPO = 'https://github.com/Renvenge/observatorio-brasil';
const LOCAL = ['localhost','127.0.0.1'].includes(location.hostname);
const FEED = LOCAL ? './current.json' : 'https://raw.githubusercontent.com/Renvenge/observatorio-brasil/data/current.json';
let data = null, view = 'contracts', page = 1, filtered = [], busy = false;
const nf = new Intl.NumberFormat('pt-BR');
const money = v => v === null || v === undefined || v === '' || !Number.isFinite(Number(v)) ? 'Não informado' : Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc = v => String(v ?? 'Não informado').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = v => {if(!v)return 'Não informado';const d=new Date(v);return isNaN(d)?'Data inválida':d.toLocaleString('pt-BR',{timeZone:'America/Fortaleza'});};
const link = (url,label) => {try{const u=new URL(url);if(u.protocol!=='https:')return esc(label);return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;}catch{return esc(label);}};
const pretty = obj => `<pre class="data-json">${esc(JSON.stringify(obj,null,2))}</pre>`;
const norm = v => String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const fact = (label,value) => `<div><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;
function message(text,warn=false){$('message').textContent=text;$('message').classList.toggle('warn',warn);}
async function load(){
 if(busy)return;busy=true;$('reload').disabled=true;
 try{const response=await fetch(FEED,{cache:'no-store',signal:AbortSignal.timeout(60000)});if(!response.ok)throw new Error('HTTP '+response.status);const next=await response.json();if(next.meta?.schema_version!==2||!Array.isArray(next.contracts)||!Array.isArray(next.works))throw new Error('Formato inválido');data=next;
 $('updated').textContent='Última publicação: '+date(data.meta.generated_at)+' (Brasília)';
 const old=(Date.now()-new Date(data.meta.generated_at).getTime())>12*3600000;
 message(LOCAL?'Prévia local com dados reais de uma coleta limitada. A base publicada pode ser maior.':old?'A publicação está há mais de 12 horas sem atualização. Consulte Fontes e cobertura e o estado do monitor.':'Alertas são hipóteses para conferência. Não comprovam corrupção e não atribuem culpa. Coleta prevista a cada 6 horas; cobertura parcial.',old||LOCAL);
 for(const [id,value] of [['count-contracts',data.meta.contracts],['count-works',data.meta.works],['count-findings',data.meta.findings],['count-assessed',data.meta.ai.assessed]])$(id).textContent=nf.format(value);
 const selected=$('uf').value;$('uf').innerHTML='<option value="">Todo o Brasil</option>'+[...new Set([...data.contracts,...data.works].map(r=>r.uf).filter(Boolean))].sort().map(uf=>`<option value="${esc(uf)}">${esc(uf)}</option>`).join('');$('uf').value=selected;
 render();
 }catch(e){message(data?'Não foi possível atualizar agora. Exibindo a última base carregada nesta página, com a data acima.':'A base pública ainda não está disponível. Consulte a execução do monitor no GitHub e tente atualizar. Nenhum resultado foi inventado.',true);$('updated').textContent=data?'Última base carregada: '+date(data.meta.generated_at):'Aguardando publicação da base';if(!data)$('rows').innerHTML=`<tr><td colspan="5" class="empty">Dados indisponíveis no momento. ${link(REPO+'/actions','Ver monitor')}</td></tr>`;}
 finally{busy=false;$('reload').disabled=false;}
}
function render(){
 $('explorer').hidden=view==='coverage';$('coverage').hidden=view!=='coverage';
 document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false');});
 if(view==='coverage'){renderCoverage();return;}if(!data)return;
 if(view==='associations'){renderAssociations();return;}
 const works=view==='works';$('section-title').textContent=works?'Obras e execução':'Explore os contratos';$('section-subtitle').textContent=works?'Investimento previsto, avanço físico e pagamentos são informações distintas.':'Cada registro tem uma fonte. Cada sinal precisa de contexto.';
 $('only-alerts').parentElement.hidden=works;$('sort').disabled=works;
 const query=norm($('search').value),uf=$('uf').value;
 filtered=data[view].filter(r=>(!uf||r.uf===uf)&&(!query||norm([r.id,r.organization,r.city,r.supplier,r.object,r.name].join(' ')).includes(query))&&(works||!$('only-alerts').checked||r.findings.length));
 const sort=$('sort').value;if(!works)filtered.sort((a,b)=>sort==='alerts'?b.findings.length-a.findings.length:sort==='value'?(b.value??-1)-(a.value??-1):String(b.published??'').localeCompare(String(a.published??'')));
 const pages=Math.max(1,Math.ceil(filtered.length/25));page=Math.min(page,pages);$('results').textContent=nf.format(filtered.length)+' '+(works?'obras':'contratos')+' nesta seleção';$('page').textContent=`Página ${page} de ${pages}`;$('prev').disabled=page===1;$('next').disabled=page===pages;$('export').disabled=!filtered.length;
 $('table-head').innerHTML=works?'<tr><th>Obra / responsável</th><th>UF</th><th>Situação na fonte</th><th>Execução</th></tr>':'<tr><th>Órgão / objeto</th><th>Localidade</th><th>Valor contratado</th><th>Sinais</th></tr>';
 $('rows').innerHTML=filtered.slice((page-1)*25,page*25).map((r,i)=>works?`<tr><td><button class="open" data-row="${i}"><strong>${esc(r.name)}</strong></button><small>${esc(r.organization)}</small></td><td>${esc(r.uf)}</td><td>${esc(r.status)}</td><td><span class="badge neutral">${r.expenses===null?'Ainda não consultada':r.expenses.length?'Dados disponíveis':'Sem registros retornados'}</span></td></tr>`:`<tr><td><button class="open" data-row="${i}"><strong>${esc(r.organization)}</strong></button><div class="object">${esc(r.object)}</div><small>${esc(r.id)}</small></td><td>${esc(r.city)}<small>${esc(r.uf)}</small></td><td class="money">${money(r.value)}<small>${r.revenue===true?'Receita contratual':r.revenue===false?'Contrato de despesa':'Natureza não informada'} · não é pagamento</small></td><td><span class="badge ${r.findings.length?'':'neutral'}">${r.findings.length?r.findings.length+' para conferir':'Sem sinal gerado'}</span>${r.findings.length?'<small>'+r.findings.map(f=>esc(findingLabel(f))).join('<br>')+'</small>':''}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Nenhum registro nesta seleção. Tente outro termo ou estado.</td></tr>';
 $('rows').querySelectorAll('[data-row]').forEach(b=>b.onclick=()=>openRecord(filtered[(page-1)*25+Number(b.dataset.row)],works));
}
function show(content){$('detail-content').innerHTML=content;$('detail').showModal();$('detail').scrollTop=0;}
function openRecord(r,works){
 let content=`<div class="eyebrow">${works?'OBRA PÚBLICA':'CONTRATO PÚBLICO'} · ${esc(r.uf)}</div><h2>${esc(works?r.name:r.organization)}</h2><p>${esc(works?r.organization:r.object)}</p><p>${link(r.source,'Consultar registro oficial')} · <span class="small">${esc(r.id)}</span></p>`;
 if(works){content+=`<div class="facts">${fact('Situação na fonte',r.status)}${fact('Fim previsto',r.expected_end)}${fact('Fim efetivo',r.actual_end)}${fact('Versão observada em',date(r.checked_at))}</div><h3>Investimento previsto</h3>${pretty(r.investments)}<h3>Execução financeira</h3><p class="small">Valores de etapas diferentes não devem ser somados. Ausência de registros não significa ausência de gasto.</p>`;
 content+=r.expenses===null?'<p>A execução financeira desta obra ainda não foi consultada com sucesso.</p>':r.expenses.length?`<div class="table-wrap"><table><thead><tr><th>Empenho</th><th>Valor empenhado</th><th>Liquidado</th><th>Pago</th><th>Restos pagos</th></tr></thead><tbody>${r.expenses.map(e=>`<tr><td>${esc(e.nr_empenho)}<small>${esc(e.data_emissao)}</small></td><td>${money(e.valor_empenho)}</td><td>${money(e.liquidado)}</td><td>${money(e.pago)}</td><td>${money(e.rppago)}</td></tr>`).join('')}</tbody></table></div>`:'<p>A fonte não retornou registros financeiros na consulta desta obra.</p>';
 content+=r.financial_source?link(r.financial_source,'Fonte da execução financeira'):'';content+='<h3>Execução física informada</h3>'+(r.physical===null?'<p>Ainda não consultada.</p>':r.physical.length?pretty(r.physical):'<p>Sem registros retornados pela fonte.</p>');
 }else{
 content+=`<div class="facts">${fact('Fornecedor',r.supplier)}${fact('Cidade / UF',[r.city,r.uf].filter(Boolean).join(' / '))}${fact('Valor inicial',money(r.initial))}${fact('Valor global contratado',money(r.value))}${fact('Início da vigência',r.start)}${fact('Fim da vigência',r.end)}${fact('Última consulta',date(r.checked_at))}${fact('Natureza',r.revenue===true?'Receita':r.revenue===false?'Despesa':'Não informada')}</div><h3>Sinais para conferir (${r.findings.length})</h3>`;
 content+=r.findings.map(f=>renderFinding(f,r)).join('')||'<p>Nenhum sinal foi gerado pelos critérios disponíveis. Isso não comprova regularidade.</p>';
 content+='<h3>Versões observadas</h3><p class="small">Histórico desde o início das coletas; pode não conter todas as alterações do contrato.</p>'+r.revisions.map(v=>`<p class="small">${date(v.at)} · valor global ${money(v.value)} · fim ${esc(v.end)}</p>`).join('');
 content+='<h3>Aditivos, arquivos e histórico oficial</h3>'+(r.documents.length?r.documents.map(d=>`<p>${link(d.source,({termos:'Termos e aditivos',arquivos:'Arquivos e documentos',historico:'Histórico da fonte'})[d.type]||d.type)}</p>`).join(''):'<p>Este contrato ainda está na fila de consulta dos documentos.</p>')+`<details><summary>Dados técnicos da cópia (opcional)</summary><p class="small">SHA-256 verifica a cópia coletada, não a veracidade da informação.</p>${pretty({sha256:r.sha256,contract_id:r.id})}</details>`;
 if(r.political_matches)content+=`<h3>Correspondências societárias a conferir</h3><p>${r.political_matches} correspondência(s) entre candidatura e pessoa no quadro societário do fornecedor. Não é um alerta financeiro nem identidade confirmada.</p><button id="see-associations">Ver fontes e correspondências</button>`;
 }show(content);
 if($('see-associations'))$('see-associations').onclick=()=>{ $('detail').close(); $('search').value=r.id; $('uf').value=''; view='associations';page=1;render(); }; 
}
function renderCoverage(){
 const names={cgu:'Portal da Transparência',obras:'Obrasgov · cadastro',obras_execucao:'Obrasgov · execução',pncp_revisitas:'PNCP · contratos antigos'};
 const states={ok:'Consulta concluída',partial:'Cobertura parcial',failed:'Falha na consulta',credentials_required:'Acesso pendente'};
 if(!data){$('coverage').innerHTML=`<div class="coverage-content"><h2>Fontes e cobertura</h2><p>A base ainda não está disponível.</p>${link(REPO+'/actions','Acompanhar coleta')}</div>`;return;}
 const m=data.meta,run=m.runs[0];
 $('coverage').innerHTML=`<div class="coverage-content"><h2>O que estamos acompanhando</h2><p class="small">Atualização prevista a cada seis horas. Fontes podem atrasar; nenhuma base representa todo o gasto público.</p><article class="source-card"><h3>PNCP · publicações <span class="badge neutral">${esc(run?.status==='complete'?'Janela consultada':run?.status==='failed'?'Coleta com falha':'Consulta parcial')}</span></h3><p>${run?`Última janela: ${esc(run.start)} a ${esc(run.end)} · ${nf.format(run.records)} registros recebidos.`:'Nenhuma coleta registrada.'}</p><p>Busca por publicação; revisitas acompanham alterações de contratos antigos gradualmente.</p></article>${m.sources.map(s=>`<article class="source-card"><h3>${esc(names[s.name]||s.name)} <span class="badge neutral">${esc(states[s.status]||s.status)}</span></h3><p>${esc(s.message)}</p><p>Última tentativa: ${date(s.checked_at)}</p><details><summary>Cobertura e diagnóstico</summary>${pretty(s.metadata)}</details></article>`).join('')}<h3>Revisão dos alertas</h3><div class="facts">${fact('Hipóteses sustentadas',m.calibration.counts.supported)}${fact('Falsos positivos revisados',m.calibration.counts.false_positive)}${fact('Inconclusivos',m.calibration.counts.inconclusive)}${fact('Revisões de versões anteriores',m.calibration.counts.stale)}</div><p>Proporção sustentada entre revisados: ${m.calibration.precision_among_reviewed===null?'ainda não medida':(m.calibration.precision_among_reviewed*100).toFixed(1)+'%'}.</p><p class="small">${esc(m.calibration.limitation)}</p><h3>Limites da IA</h3><p class="small">${esc(m.ai.limitations)}</p><p class="small">Dados ausentes: ${nf.format(m.ai.excluded_missing_data)} · grupos pequenos ou constantes: ${nf.format(m.ai.excluded_small_or_constant_groups)} registros não avaliados.</p><h3>Integrações que dependem de acesso e validação</h3><p class="small">A situação da integração CGU está detalhada acima. Os cruzamentos TSE/Receita são correspondências a conferir, com cobertura indicada em cada fonte. Comparações automáticas SINAPI/SICRO, análise de PDFs, bases locais e cobertura histórica integral ainda não estão ativas. Não atribuímos responsabilidade pessoal a políticos pela data de um contrato.</p><p>${link(REPO+'/actions','Estado do monitor')} · ${link(REPO+'/tree/data','Histórico e dados abertos')} · ${link(REPO+'#fontes-e-cobertura','Documentação')}</p></div>`;
}
function download(){if(view==='associations'){downloadAssociations();return;}const rows=filtered.map(r=>view==='works'?{id:r.id,obra:r.name,uf:r.uf,situacao:r.status,fonte:r.source}:{id:r.id,orgao:r.organization,cidade:r.city,uf:r.uf,fornecedor:r.supplier,objeto:r.object,valor_contratado:r.value,sinais:r.findings.length,fonte:r.source});if(!rows.length)return;const keys=Object.keys(rows[0]);const cell=v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const csv='\uFEFF'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='observatorio-'+view+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;page=1;render();});
for(const id of ['search','uf','sort','only-alerts'])$(id).addEventListener(id==='search'?'input':'change',()=>{page=1;render();});
$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};$('reload').onclick=load;$('export').onclick=download;$('close').onclick=()=>$('detail').close();
$('method').onclick=()=>show('<div class="eyebrow">METODOLOGIA ABERTA</div><h2>Uma pista precisa de contexto.</h2><p>O Observatório reúne registros de fontes oficiais e aplica critérios exploratórios. Uma variação de valor, um cadastro repetido ou uma combinação estatística incomum pode ter uma explicação legítima.</p><h3>Como a IA encontra padrões</h3><p>O modelo Isolation Forest compara valor, variação relativa e duração em grupos por UF, esfera, categoria e tipo de contrato. Exige ao menos 30 registros e variação suficiente. Sugere nomes descritivos para combinações incomuns; não certifica fraude nem a novidade de um esquema.</p><h3>Antes de tirar uma conclusão</h3><p>Consulte os documentos, confira aditivos, quantidades e justificativas, compare condições equivalentes e procure evidências independentes. O valor contratado não é o valor pago.</p><h3>O que os números não dizem</h3><p>Ausência de alerta não prova regularidade. A precisão da detecção de corrupção não foi medida. A base é parcial e a responsabilidade de uma pessoa não pode ser deduzida apenas do órgão ou da data.</p>'+link(REPO,'Conhecer o projeto e os critérios'));
load();setInterval(load,300000);
